"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()



from os import getenv
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure---98%^v$!6h3qkb#4$nb_kj$o+g8@5vl_+*h6z_^27(y75o3i4'
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = ['*']


# DEBUG = os.getenv("DEBUG") == 'True'
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


       # Local apps
    # 'myapp',
    "users",
    'crossborder',
    "ai",
    "buyrite",
    'laundry',
    'store',
    "smart_office",
      'django.contrib.humanize',


              



    'django_otp',
    'crispy_bootstrap5',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'crispy_forms',
     'rest_framework',
         'tinymce',
         'taggit',

    'django_htmx',  # optional, for enhanced HTMX support


        # Allauth apps
    
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Add providers if needed, e.g.:
    'allauth.socialaccount.providers.google',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
     'allauth.account.middleware.AccountMiddleware',  # 👈 Required for django-allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',  # ✅ valid middlewar

    # 'django-htmx-ext.middleware.HtmxExtMiddleware,  "# optional, for enhanced HTMX support

# 'myproject.middleware.domain_router.DomainRouterMiddleware',

]

ROOT_URLCONF = 'myproject.urls'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
                'DIRS': [os.path.join(BASE_DIR, 'templates')],  # or Path(BASE_DIR) / "templates"
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'buyrite.context_processors.vin_form_processor',


                 "django.template.context_processors.debug",
               

            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        "timeout": 20,  # default is 5 seconds

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth settings
AUTH_USER_MODEL = 'users.User'




# ✅ Required for django-allauth
SITE_ID = 1

# Django-allauth configuration
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Change to 'mandatory' in production






# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
# ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_ADAPTER = 'users.adapter.MySocialAccountAdapter'
# SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'


# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_UNIQUE_EMAIL = True
# SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "none"



# Authentication redirects
LOGIN_URL = 'users:login'
LOGOUT_REDIRECT_URL = 'users:login'
LOGIN_REDIRECT_URL = 'users:home'  # Assuming 'home' is the name of your buyrite app's home view/
# LOGIN_REDIRECT_URL = '/'  # Assuming 'home' is the name of your buyrite app's home view

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True  # ✅ Enable TLS for Gmail
# EMAIL_USE_SSL = False  # ✅ Must be False if TLS is True
# EMAIL_HOST_USER = "upwardwave.dignity@gmail.com"
# EMAIL_HOST_PASSWORD = "vudtoktjbahbzhbv"

# DEFAULT_FROM_EMAIL = 'Dignity Concept <upwardwave.dignity@gmail.com>'

DEFAULT_FROM_EMAIL = 'Dignity Concept <upwardwave.dignity@gmail.com>'

import os

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'solutions@dignityconcept.tech')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.dignityconcept.tech')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 465))

EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'True') == 'True'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



# ==============================================================================
#  Default
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_ID = 1

STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
# Base URL of your application, used for absolute URL generation.
# Replace with your actual domain when deploying.
SITE_URL = 'http://localhost:8000'
SITE_DOMAIN = "https://demos.kupiansolutions.com"




# settings.py
# ... other settings

# PayPal API Settings


# Use 'https://api.sandbox.paypal.com' for testing
# Use 'https://api.paypal.com' for production
PAYPAL_BASE_URL = 'https://api.sandbox.paypal.com'
PAYPAL_MODE = 'sandbox' # Use 'live' for production
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")

# Base URL of your application, used for absolute URL generation.
SITE_URL = 'http://localhost:8000'




STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/ogdmvge43vwuhn7ascystm3r6p5qhwdx6d4tweotiiihfre3/tinymce/8/tinymce.min.js'
# TINYMCE_COMPRESSOR = False




# TINYMCE_COMPRESSOR = False

# TINYMCE_JS_URL = '/static/js/tinymce.min.js'










# TINYMCE_JS_URL = os.path.join(STATIC_URL, "tinymce/tinymce.min.js")
# TINYMCE_JS_URL = '/static/js/tinymce.min.js'

# TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/no-api-key/tinymce/8/tinymce.min.js'
# TINYMCE_COMPRESSOR = False
# TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/ogdmvge43vwuhn7ascystm3r6p5qhwdx6d4tweotiiihfre3/tinymce/8/tinymce.min.js'


# ogdmvge43vwuhn7ascystm3r6p5qhwdx6d4tweotiiihfre3
# TINYMCE_DEFAULT_CONFIG = {
#     'height': 360,
#     'width': 800,
#     'plugins': 'link image preview code',
#     'toolbar': 'undo redo | bold italic | alignleft aligncenter alignright | code',
    
# }


# # TINYMCE_JS_URL = 'http://debug.example.org/tiny_mce/tiny_mce_src.js'

TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",  # Editor height
    "width": "960px",   # Editor width

    "menubar": "file edit view insert format tools table help",  # Top menu bar options

    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
               "fullscreen insertdatetime media table paste code help wordcount spellchecker",  # Enabled plugins

    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
               "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
               "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
               "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
               "a11ycheck ltr rtl | showcomments addcomment code",  # Toolbar layout

    "custom_undo_redo_levels": 10,  # Number of undo/redo steps

    # "language": "es_ES",  # Optional: force Spanish language
       "browser_spellcheck": True,
    "contextmenu": False,


    "plugins": "image code wordcount",
    "toolbar": "undo redo | image code wordcount",
    "images_upload_url": "/upload_image/",
    "automatic_uploads": True,
    "file_picker_types": "image",


}


TINYMCE_SPELLCHECKER = True
# TINYMCE_COMPRESSOR = True
# TINYMCE_EXTRA_MEDIA = {
#     'css': {
#         'all': [
#             ...
#         ],
#     },
#     'js': [
#         ...
#     ],
# }
# TINYMCE_API_KEY = 'ogdmvge43vwuhn7ascystm3r6p5qhwdx6d4tweotiiihfre3'



EXTERNAL_API_BASE_URL = "https://api.vehicledatabases.com/saleshistory/"
EXTERNAL_API_AUTH_KEY = "e9e7dba6a79e11f0812f0242ac120002" # Replace this